server:
  port: 8080
spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        default_schema: public
        ddl-auto: none
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/geminis
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: estrada123
    hikari:
      idle-timeout: 10000
      pool-name: GememiniApiPool
      maximum-pool-size: 5
