# Server properties
server:
  servlet:
    context-path: /geminis-api
  port: 8080
# Spring properties
spring:
  # Dev is active by default. This value can be overwritten by java arg param
  profiles:
    active: qas
  application:
    name: api
  messages:
    basename: bundles/apiLanguageBundle
  jackson:
    serialization:
      write-dates-as-timestamps: false
  jmx:
    default-domain: geminis-api
